Mes aides garages extract and reshape
betagouv/data-inclusion-scripts pull request #3
Opened 2022-08-17 13:25 UTC by Aurel-Allard

2022-08-17 14:55 UTC, vmttn requested changes
Cool ! C'est parti :
* Pour le nom du fichier tu peux mettre un underscore `mes-aides.py` -> `mes_aides.py` c'est la convention en python.
* Pour les commentaires, il faut faire attention au "Comments Repeat Code". J'aime bien le moto : "Comments should describe things that arent obvious from code". Il n'y a pas de regle absolue (par exemple si ça facilite la lecture/réduit l'effort cognitif sur le code) :)
* pour les tests, tu peux écrire un test unitaire en t'inspirant des tests pour les autres mappings. Si tu veux, tu peux utiliser `pytest --pdb` pour récupérer rapidement un résultat pour ton test : cf https://simonwillison.net/2020/Feb/11/cheating-at-unit-tests-pytest-black/.

2022-08-17 14:55 UTC, vmttn commented on src/data_inclusion/tasks/sources/mes-aides.py
> +GARAGES_SOLIDAIRES_SOURCE_STR = "garages solidaires"
```suggestion
MES_AIDES_SOURCE_STR = "mes-aides"
```
Pour le moment, le champs `source` identifie le partenaire.

(nb: C'est notamment ce que l'on fait dans pour `itou`. Comme tu peux le voir dans `./dags/main.py` : on moissonne 2 tables différentes (`structures/?type=siae` et `structures/?type=orga`) et on attribut à l'ensemble `source=itou`. Effectivement ça peut être interessant de distinguer les datasets, mais par cohérence je te propose de garder `source=<nom_du_partenaire>` et de changer globalement par la suite)

2022-08-17 14:55 UTC, vmttn commented on src/data_inclusion/tasks/sources/mes-aides.py
> +# Imports
tu peux retirer ce commentaire

2022-08-17 14:55 UTC, vmttn commented on src/data_inclusion/tasks/sources/mes-aides.py
> +from dateutil.parser import parse as dateutil_parse
J'ai l'impression que les imports ne sont pas triés. Est-ce que tu as bien installé les precommits ?
j'ai ajouté un `CONTRIBUTING.md` dans le repo pour détailler ça ce matin, mais c'est la même idée que dans le repo d'analyse : si tu as un `.pre-commit-config.yaml` à la base du repo c'est qu'il y a des precommit : `pre-commit install`

2022-08-17 14:55 UTC, vmttn commented on src/data_inclusion/tasks/sources/mes-aides.py
> +    # Output path
tu peux retirer ce commentaire

2022-08-17 14:55 UTC, vmttn commented on src/data_inclusion/tasks/sources/mes-aides.py
> +    # Loading into a dataframe
tu peux retirer ce commentaire :)

2022-08-17 14:55 UTC, vmttn commented on src/data_inclusion/tasks/sources/mes-aides.py
> +    #### presentation_resume -> CRITERE A VALIDER
est-ce qu'il y a un champ explicite dans les données de mes aides pour la description ? Si il n'y en a pas, on peut laisser `None`.
De manière générale, on veut éviter au maximum d'éditer les données. Les transformations qu'on s'autorise c'est du formatage et parfois de l'enrichissement pour que les données soient:
* visualisable sur une carto -> géocodage
* plus facilement déduplicable -> siretisation
* catégorisées par typologie -> on essaie d'extraire cette info

2022-08-17 14:55 UTC, vmttn commented on src/data_inclusion/tasks/sources/mes-aides.py
> +    output_df = output_df.assign(id=input_df["ID"].astype(str))
il me semble que la colonne identifiant mes aides contient déjà des objets de type `str` ? si c'est le cas tu peux retirer `.astype(str)`

2022-08-17 14:55 UTC, vmttn commented on src/data_inclusion/tasks/sources/mes-aides.py
> +    #### typologie
à défault ça sera `models.Typologie.Autre`
Il faudrait typiquement demander l'avis d'Agathe, mais à priori ça sera `Autre`

2022-08-17 14:56 UTC, vmttn commented on .gitignore
> +.env
J'ai fixé ça ce matin. Tu peux merge `master` dans ta branche pour récupérer les changements.

2022-08-17 23:08 UTC, Aurel-Allard commented
@vmttn 

Prise en compte des changements sollicités pour validation :
- Descente des points un à un
- La `structure_parente` me semble cohérent mais j'aimerais m'en assurer
- Le `lien_source` est laissé en critère à valider (toujours des doutes quant au vis-à-vis avec `site_web`)

👉 J'attends ta validation pour mettre en place le test
🤔 Je me disais qu'un fichier de requirements pourrait être utile, je peux m'en occuper

nb : Génial ces pre-commits, effectivement je n'avais pas fait l'install, j'en prends plein la tête c'est chouette !

2022-08-25 16:59 UTC, vmttn commented
Pour moi tu peux mettre en place les tests :)

> Je me disais qu'un fichier de requirements pourrait être utile, je peux m'en occuper

Effectivement ça pourrait être bien d'uniformiser ça entre les repos, mais à moins que tu aies eu un problème, je te propose de remettre ça à plus tard ;)

2022-08-30 14:34 UTC, Aurel-Allard commented
Pour info : j'ai découvert après coup l'extraction du schema depuis le repo dans setup.py, d'où le revert présent.

2022-09-08 12:41 UTC, Aurel-Allard commented
Tests et preprocess fonctionnels.

@vmttn Nous pouvons nous passer de pyairtable afin de passer par une url source.
Peux-tu me confirmer ce changement à réaliser ?

2022-09-12 15:58 UTC, vmttn reviewed
pour le nommage des branches : `aallard/feat/mes-aides-garages-extract-and-reshape`

2022-09-12 15:58 UTC, vmttn commented on src/data_inclusion/scripts/tasks/sources/mes_aides.py
> +def extract_data(api_key: str, base_id: str, table_name: str) -> Path:
```suggestion
def extract_data(src: str, token: str, **kwargs) -> Path:
```

en fait il faut respecter la même interface que dans les autres `extract_data`

où `src` est l'url vers la source et peut provenir par exemple de la cli `data_inclusion preprocess <SRC_TYPE> <SRC_URL> --token <TOKEN>` (cf `data_inclusion/scripts/entrypoints/cli.py:33`).
idem pour `token`

2022-09-12 15:58 UTC, vmttn commented on src/data_inclusion/scripts/tasks/sources/mes_aides.py
> +def extract_data(api_key: str, base_id: str, table_name: str) -> Path:
tu peux extraire `base_id` et `table_id` depuis l'url de la table sur airtable : cf https://support.airtable.com/docs/understanding-airtable-ids

2022-09-12 15:58 UTC, vmttn commented on src/data_inclusion/scripts/tasks/sources/mes_aides.py
> +
```suggestion
    output_df = output_df.replace([np.nan, ""], None)
```

pour simplifier, on remplace les strings vides par des valeurs nulles

2022-09-12 15:58 UTC, vmttn commented on src/data_inclusion/scripts/tasks/sources/mes_aides.py
> +    # lien_source -> CRITERE A VALIDER
```suggestion
    # lien_source
```
pas de lien vers le site disponible dans les données malheureusment :/

2022-09-12 15:58 UTC, vmttn commented on src/data_inclusion/scripts/tasks/sources/mes_aides.py
> +    output_df = output_df.assign(structure_parente=input_df["Partenaire Nom"])
```suggestion
    output_df = output_df.assign(structure_parente=None)
```
Ce champs référence le champs `id` d'une autre ligne du jeu de données.
Il y a peut-être des antennes dans les données, mais leur schéma ne permet pas de retrouver ce lien facilement.
On peut laisser à la valeur nulle pour le moment

2022-09-12 15:58 UTC, vmttn commented on src/data_inclusion/scripts/tasks/sources/mes_aides.py
> +    table.all()
```suggestion
```

2022-09-12 21:06 UTC, Aurel-Allard commented
Divers changements dont celui de l'extract effectués.
Preprocess à vérifier.

2022-09-14 10:26 UTC, vmttn approved these changes

2022-09-14 10:30 UTC, vmttn approved these changes

2022-09-14 10:36 UTC, merged