Finess mapping scripts
betagouv/data-inclusion-scripts pull request #5
Opened 2022-09-08 12:27 UTC by Aurel-Allard

Tests et preprocess fonctionnels.

[Sujets à considérer par ailleurs](https://github.com/betagouv/data-inclusion-analyse/pull/3#issuecomment-1240645865)

2022-09-13 16:17 UTC, vmttn requested changes

2022-09-13 16:17 UTC, vmttn commented on src/data_inclusion/scripts/tasks/sources/finess.py
> +        + input_df.telephone.fillna(0.0).astype(int).astype(str).replace("00", None)
```suggestion
        + input_df.telephone.fillna(0.0).astype(int).astype(str).replace("0", None)
```

2022-09-13 16:17 UTC, vmttn commented on tests/unit/test_finess.py
> +                "Unnamed: 0": 17479,
est-ce que cette colonne existe vraiment dans les données d'origine ?

2022-09-13 16:17 UTC, vmttn commented on src/data_inclusion/scripts/tasks/sources/finess.py
> +    # Transform metropole coordinates
est-ce que tu peux passer ces 2 sections au niveau des sections `# longitude` et `# latitude` stp ?

2022-09-13 16:17 UTC, vmttn commented on tests/unit/test_finess.py
> +            "siret": 40762764500010,
"40762764500010"

2022-09-13 19:49 UTC, Aurel-Allard commented on tests/unit/test_finess.py
> +                "Unnamed: 0": 17479,
Oui ! ;)

2022-09-13 19:50 UTC, Aurel-Allard commented on tests/unit/test_finess.py
> +                "Unnamed: 0": 17479,
Oui c'est une colonne d'index :)

2022-09-13 20:08 UTC, Aurel-Allard commented
Divers changements dont celui de l'extract effectués.
Preprocess à vérifier.

2022-09-27 10:08 UTC, vmttn approved these changes

2022-09-27 10:09 UTC, merged